// Generated by CoffeeScript 1.8.0
(function() {
  var ecdsa, exports, make_message, parseSig, serializeSig, sha256, sign_response, verifier;

  ecdsa = require('ecdsa');

  serializeSig = ecdsa.serializeSig, parseSig = ecdsa.parseSig;

  sha256 = require('crypto-hashing').sha256;

  sign_response = function(key, opt) {
    var curve, req_filter;
    if (opt == null) {
      opt = {};
    }
    req_filter = opt.req_filter || function(req) {
      return req.method === 'GET' && ((req.query.sign_resp != null) || req.get('X-Sign-Response'));
    };
    curve = ecdsa(opt.curve || 'secp256k1');
    return function(req, res, next) {
      var send;
      if (req_filter(req)) {
        send = res.send;
        res.send = function(code, body) {
          var msg, sig;
          if (body == null) {
            body = code;
            code = null;
          }
          if (typeof body === 'string') {
            msg = make_message(req.method, req.url, body);
            sig = new Buffer(serializeSig(curve.sign(msg, key)));
            res.set('X-Response-Sig', sig.toString('base64'));
          }
          if (code != null) {
            return send.call(this, code, body);
          } else {
            return send.call(this, body);
          }
        };
      }
      return next(null);
    };
  };

  make_message = function(method, path, body) {
    method = method.toUpperCase();
    return sha256('ecdsa-signed-response/' + JSON.stringify({
      method: method,
      path: path,
      body: body
    }));
  };

  verifier = function(pubkey, curve_name) {
    var curve;
    if (curve_name == null) {
      curve_name = 'secp256k1';
    }
    curve = ecdsa(curve_name);
    return function(method, path, body, sig) {
      if (typeof sig === 'string') {
        sig = new Buffer(sig, 'base64');
      }
      return curve.verify(make_message(method, path, body), parseSig(sig), pubkey);
    };
  };

  exports = module.exports = sign_response;

  exports.sign_response = sign_response;

  exports.make_message = make_message;

  exports.verifier = verifier;

}).call(this);
